// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7HEcKQCV3PfRBzpcy2FQBhM-H1f6-c-c',
    appId: '1:256741630329:web:fde4f119a1c13ae7098fa8',
    messagingSenderId: '256741630329',
    projectId: 'trekking-maua',
    authDomain: 'trekking-maua.firebaseapp.com',
    storageBucket: 'trekking-maua.appspot.com',
    measurementId: 'G-YSF2QVC33C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCvh3vtH0mRYD9i0jw8_As0tqLuCkwv5w',
    appId: '1:256741630329:android:a0cda78ccde5a156098fa8',
    messagingSenderId: '256741630329',
    projectId: 'trekking-maua',
    storageBucket: 'trekking-maua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs0I49aQZacAL2VtDVWlW69Ql5-BGWf_s',
    appId: '1:256741630329:ios:2c0527fb5f97bf3d098fa8',
    messagingSenderId: '256741630329',
    projectId: 'trekking-maua',
    storageBucket: 'trekking-maua.appspot.com',
    iosBundleId: 'com.example.mauaTreckingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs0I49aQZacAL2VtDVWlW69Ql5-BGWf_s',
    appId: '1:256741630329:ios:2c0527fb5f97bf3d098fa8',
    messagingSenderId: '256741630329',
    projectId: 'trekking-maua',
    storageBucket: 'trekking-maua.appspot.com',
    iosBundleId: 'com.example.mauaTreckingProject',
  );

}